### ISSUE TITLE
Interpretation of difference in CLR 

### ISSUE THREAD

**Issue by noelzach** [FrederickHuangLin/ANCOM#10]
Hi, thank you for this script! I really enjoy the ANCOM method and the tutorial is nice and easy to follow. 

I just have a question about interpreting the mean difference in CLR for an OTU. The way I understand it is like a log fold change? So a 2 mean CLR difference would mean a two fold change difference in abundance? Or in R the log function is the natural log so does 2 mean e^2 fold difference in abundance? 

Sorry if this more of a basic question, but just trying to understand the results better and would appreciate any guidance. 

thanks!

**Comment by FrederickHuangLin** [comment]
Hi,

Thanks for using ANCOM! 

The CLR transformation is short for [Center logratio transform](https://en.wikipedia.org/wiki/Compositional_data) which is commonly used in compositional data analysis.

For example, if we have two groups here, say control group and treatment group, basically, the OTU table will be CLR transformed. Then for each taxon, the mean transformed abundance is calculated for each group, and we take the difference.

Hope it is clear :)

Huang

**Comment by noelzach** [comment]
Hi Huang, 

Thanks for the explanation. I understand what a CLR transformation is, but I guess my question mainly had to do with the magnitude of change. In other words, what does a mean CLR difference of 2 mean exactly in terms of the relative abundance for that OTU?

**Comment by FrederickHuangLin** [comment]
Sorry I didn't fully answer your question. It might not be a perfect interpretation, but consider a minimal example with two groups (control and treatment) and we are interested in one taxon (taxon A).

For taxon A, CLR (control) = 2, which means **with respect to the geometric mean abundance of all taxa**, the mean log (natural log) fold change of relative/absolute abundances (they are the same by the nature of logratio transformation) in controls is 2; while CLR (treatment) = 4 means **with respect to the geometric mean abundance of all taxa**, the mean log (natural log) fold change of relative/absolute abundances in subjects of treatment is 4. Thus, the mean difference in CLR is: CLR (treatment) - CLR (control) = 2, meaning that **with respect to the geometric mean abundance of all taxa**, subjects in treatment group has greater log fold change (on average) of relative/absolute abundances than controls in a magnitude of 2.

Please let me know if it is still unclear,

Huang

**Comment by noelzach** [comment]
That is much clearer, thank you! I just don't think I knew how to word it correctly. But basically the mean difference for any taxon is the mean log fold change (natural log) with respect to other all other taxa. That's nice. So if I were to put your example back in terms of fold change, could I then say that the mean abundance of subjects in the treatment group 2 fold compared to the control with respect to the geometric mean of all other taxa? Its natural log right so is FC equivalent to e^2 = 7.38 fold compared to the control with respect to the geometric mean of all other taxa? Thanks for the responses!

**Comment by FrederickHuangLin** [comment]
Hi,

Sorry for the huge delay! I am relocating and being distracted by all sorts of errands. 

I think you are right!

Best,

Huang
