### ISSUE TITLE
Problem installing ANCOM in R

### ISSUE THREAD

**Issue by Laura-ciuf** [FrederickHuangLin/ANCOM#12]
Hi there,

I am having problem installing ANCOM in my R (version 3.6.2)

I tried: 
install.packages("~/AncomR/ancom.R_1.1-2.tar.gz")
and
install.packages('ANCOM')

but I got the error
Installing package into ‘C:/Users/User/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘~/AncomR/ancom.R_1.1-2.tar.gz’ is not available (for R version 3.6.2)

I also tried installing with other R version (3.0 and 3.1), but getting the same errors. 
Someone can help?
Thanks

**Comment by ramtinz** [comment]
same problem here

**Comment by FrederickHuangLin** [comment]
Hi,

ANCOM is not an R package yet, make sure the ANCOM is uploaded and stored under your working directory, then run the following:

`source("ancom_v2.1.R")`

Best,

Huang
