### ISSUE TITLE
object 'prepro' not found

### ISSUE THREAD

**Issue by Jaimes8a** [FrederickHuangLin/ANCOM#13]
Hello. I used the script on May 21, 2020, and it worked without a problem. Today, June 9, 2020, I am running the exact same script with the same data but now I am getting errors in 
# Step 1: Data preprocessing
**These are the commands that are giving me errors**
prepro = feature_table_pre_process(feature_table, meta_data, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table 

**I get the following errors:**
Error in `[.data.frame`(meta_data, , sample_var) : 
  undefined columns selected

Error during wrapup: object 'prepro' not found
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

Thank you.

**Comment by fconstancias** [comment]
Hello, I am encontering the same error here.

**Comment by Jaimes8a** [comment]
Hello,

I'm the OP of this thread. The culprit in my case was that another loaded R package was apparently interfering with this one. My colleague thinks that it was another package that also had a "rename" function, and thus the "prepro" object didn't get created. Once the other packages were unloaded, the script worked for me.

**Comment by FrederickHuangLin** [comment]
Hi All,

Sorry for responding late! 

Just as Jaimes said, it might due the conflicts with other packages. If it is still not working, could you please upload the code you wrote with an example dataset?

Best,

Huang

**Comment by negin1986** [comment]
Yes, I had the same issue as well. Just close your R completely and run everything carefully again. It is most definitely confusing values or functions with another R session.
