### ISSUE TITLE
MetaPhlan output (relative abundance) suitable for ANCOM?

### ISSUE THREAD

**Issue by ruairirobertson** [FrederickHuangLin/ANCOM#14]
Hi Frederick,

Thanks for a great package! 

I have lots of shotgun sequencing data that I have put through MetaPhlan, which only generates relative abundance tables (rather than count tables as for 16S data). I have noticed that ANCOM states that only count data should be input, however it seems to transform to relative abundance within the package? Is there some way to use MetaPhlan data with ANCOM? I can create a pseudocount by multiplying the MetaPhlan relative abundance data by the total read count per sample but not sure if this is suitable.

Thanks for your help!

Ruairi

**Comment by FrederickHuangLin** [comment]
Hi Ruairi,

Thanks for using ANCOM!

Sure, so long as the resulting data is a count table (and follows the format stated in the user manual here), ANCOM should work as well!

Best,

Huang
