### ISSUE TITLE
How are the OTU's chosen in the results file?

### ISSUE THREAD

**Issue by samd1993** [FrederickHuangLin/ANCOM#15]
Hi,

I am wondering how the OTUs are chosen after the analyses are run? My OTU file contains thousands of OTUs but only 208 of those are reported in the results file. Are these the OTU's that pass some sort of threshold? Of these OTUs only several are significant at 0.6 or above. 

Thanks,
Sam

**Comment by FrederickHuangLin** [comment]
Hi Sam,

Yes, ANCOM does have a data preprocessing step before the main function. For example, if you set `zero_cut = 0.90`, then taxa with the proportion of zeroes greater than 90% are not included in the ANCOM analysis.

For details, you can check the usage of `feature_table_pre_process` in the README file.

Best,

Huang

**Comment by samd1993** [comment]
Ah, gotcha.  I will mess around with that. 
Thanks
