### ISSUE TITLE
ANCOM running for a day but returns no output

### ISSUE THREAD

**Issue by negin1986** [FrederickHuangLin/ANCOM#17]
Hello,

I did the following:

# INSTALL AND LOAD R PACKAGES ################################

library("doParallel")
library("DT")
library("coin")
library("exactRanksTest") # I couldn't install this one though. I get an error that this is not supported anymore and use coin instead.
library("foreach")
library("ggplot2")
library("Rcpp")
library("shiny")
library("phyloseq")
library("readr")
library("tidyverse")
source("../../scripts/2.R/ANCOM-master/scripts/ancom_v2.1.R")

# Before this step, I defined my variables on the top

# DIFFERENTIAL ABUNDANCE TEST WITH ANCOM #####################################

# Step 1: Data preprocessing -------
feature_table = otu; sample_var = sample; group_var = NULL
out_cut = 0.05; zero_cut = 0.90; lib_cut = 1000; neg_lb = FALSE

prepro <- feature_table_pre_process(feature_table, mapp, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table <- prepro$feature_table # Preprocessed feature table
meta_data <- prepro$meta_data # Preprocessed metadata
struc_zero <- prepro$structure_zeros # Structural zero info

# Step 2: ANCOM -----
main_var = main; p_adj_method = "BH"; alpha = 0.05
adj_formula = NULL; rand_formula = NULL

res <- ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, alpha, adj_formula, rand_formula)

My R gets stuck at the step of calculating res() forever. No errror, nothing. Just goes on forever. Any ideas?

Thanks!

**Comment by negin1986** [comment]
Can someone respond to this please?

**Comment by FrederickHuangLin** [comment]
Hi,

My sincere apology for responding late!

In order for me to better look into your problem, could you please provide a reproducible example of this error (i.e. an example dataset so long as it won't violate any confidential regulations)?

Best,

Huang

**Comment by negin1986** [comment]
Hi Huang,

It is difficult to provide the dataset as I am not the owner of the data and do not feel comfortable sharing. In your tutorial, you mentioned that it should take 30s. My data is big but I left it to run for more than 10 hours and nothing happened. Do you have any theory as what might have cause the issue?

Thanks!

**Comment by negin1986** [comment]
I just tried with another dataset that was much smaller and it worked. It might just be that my data is huge.

**Comment by negin1986** [comment]
This might be a question for another issue, but is there a way to add taxa labels to the volcano plot?

**Comment by FrederickHuangLin** [comment]
I totally understand your concern about sharing the data. 

Based on my experience, I do not expect that the runtime would be more than 2 hours. Could you inform me how many taxa do you have? I guess the culprit would be the "exactRanksTest" package but I will dig into it and let you know asap.

Best,

Huang

**Comment by negin1986** [comment]
Hi Huang,

I have 215580 taxa. I was not able to install exactRanksTest. However, I was able to get output for another dataset very quickly.

Thanks!

**Comment by negin1986** [comment]
I got this to work. I ended up filtering out less prevalent taxa and made the table smaller. I am using phyloseq object for this purpose and extract metadata and otu_table from that. 

The plot I get is not very informative as it does not have actual taxa names listed. Any idea how to add those to the plot? One problem I have is that I can't seem to be able to get actual taxa names instead of otu IDs. I tried setting these as rownames to the phyloseq object at a specific rank but is not possible as OTU IDs are more diverse than taxa names so taxa names will be repetitive and won't be accepted as rownames. 

Thanks!

**Comment by FrederickHuangLin** [comment]
Hi,

If you are actually not interested in OTUs, I would recommend you aggregate your feature table to a higher taxonomic level. This can avoid duplicated taxa names.

Here is an example code using `microbiome` R package.

```
OTU = otu_table(otu_table, taxa_are_rows = TRUE)
META = sample_data(meta_data)
TAX = tax_table(tax)
otu_data = phyloseq(OTU, TAX, META, tree)
family_data = aggregate_taxa(otu_data, "Family") # Suppose you are interest in family level.
```

As for annotating the volcano plot, since it is generated by `ggplot`, you can add `geom_text` to the `fig` object. For more information, you can read this [post](https://stackoverflow.com/questions/15624656/label-points-in-geom-point).

Best,

Huang
