### ISSUE TITLE
invalid formula error in repeated measure code

### ISSUE THREAD

**Issue by dhrpa** [FrederickHuangLin/ANCOM#18]
@FrederickHuangLin 
Hello,

I am trying to use repeated measures in ANCOM2. In the beginning I tried using the example dataset with the code given. 
In the step 2: ANCOM
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
           alpha, adj_formula, rand_formula, control)
Throws the following error:  Error in formula.default(object) : invalid formula
When used without control (I tried it just to see how it works) it works fine. The same is happening with my files too.

Can you help me as to why would this be happening? I am using ANCOM2 for the first time, and don't have a lot of knowledge about the same. My apologies if it is something very silly. 

Thank you

Kind regards
Dhrati Patangia

**Comment by FrederickHuangLin** [comment]
Hi Dhrati,

Sorry for responding late!

This [post](https://github.com/FrederickHuangLin/ANCOM/issues/7) would probably help!

Sometimes, specifying `control = control` instead of leaving `control` itself will solve the problem!

Best,

Huang
