### ISSUE TITLE
Where are random effects account for in lme?

### ISSUE THREAD

**Issue by dadahan** [FrederickHuangLin/ANCOM#19]
Looking at the source code from ancom_v2.1.R , it doesn't look like random effects are account for in the call for `lme`. Specifically in  ```tformula = formula(paste("x ~", main_var))```.

```
}else if (is.null(rand_formula) & !is.null(adj_formula)) {
    # Model: ANOVA
    tfun = stats::aov
    # Formula
    tformula = formula(paste("x ~", main_var, "+", adj_formula, sep = " "))
  }else if (!is.null(rand_formula)) {
    # Model: Mixed-effects model
    tfun = nlme::lme
    # Formula
    if (is.null(adj_formula)) {
      # Random intercept model
      tformula = formula(paste("x ~", main_var))
    }else {
      # Random coefficients/slope model
      tformula = formula(paste("x ~", main_var, "+", adj_formula))
    }
  }
```

**Comment by FrederickHuangLin** [comment]
Hi,

`adj_formula` is indeed only used for fixed effects; however, random effects are modeled by `rand_formula`. 

`fit = tfun(fixed = tformula, 
                   data = data.frame(x, alr_data, check.names = FALSE),
                   random = formula(rand_formula),
                   na.action = na.omit, ...)`

Best,

Huang

**Comment by dadahan** [comment]
Hi Huang,
Thank you. Where is this line you point to in the main [script](https://github.com/FrederickHuangLin/ANCOM/blob/master/scripts/ancom_v2.1.R)?

**Comment by FrederickHuangLin** [comment]
Hi,

You can find it from line 206 to line 209.

Best,

Huang

**Comment by dadahan** [comment]
Thank you. Do have/plan to add random formula to [ANCOM-BC](https://github.com/FrederickHuangLin/ANCOM-BC-Code-Archive/blob/master/scripts/ancom_bc.R)?

**Comment by FrederickHuangLin** [comment]
Yes, it will be available once our follow-up paper gets published!

Stay tuned,

Huang

**Comment by dadahan** [comment]
Thanks and good luck!
