### ISSUE TITLE
Result of ANCOM

### ISSUE THREAD

**Issue by chloelulu** [FrederickHuangLin/ANCOM#2]
Hi, 
Thanks for producing the package!
I am trying to use it, while facing some problems. ANCOM produces result with 
`taxa_id W detected_0.9 detected_0.8 detected_0.7 detected_0.6`. May I please know that can I have the exact p-value? 
Thanks.

**Comment by FrederickHuangLin** [comment]
Hi,

Thanks for using the ANCOM package! 

Unfortunately, based on the methodology of ANCOM, it is not able to provide you with a p-value for each taxon; Instead, it will inform you of which taxa are differentially abundant based on different percentiles (from 60 percentile to 90 percentile) of the test statistics. 

Usually, you can choose `detected_0.7` as the criterium to select differentially abundant taxa (which means significant taxa will have test statistics larger than 70 percentile of all test statistics). For a more stringent result, you can definitely use `detected_0.8` or `detected_0.9` instead.

We realize the limitations of ANCOM and wrote a manuscript for an updated version of it (but based on a different methodology).  The manuscript has been submitted, and once it is accepted, we will make the corresponding R package publicly available as well.

P. S. We will also push ANCOM to CRAN or Bioconductor soon (probably in the middle of this year), stay tuned!

Hope it helps,

Huang

**Comment by chloelulu** [comment]
Really appreciate the quick reply! It is much more understandable now! Thanks! :-)

**Comment by FrederickHuangLin** [comment]
> Really appreciate the quick reply! It is much more understandable now! Thanks! :-)

You are welcome!
