### ISSUE TITLE
Direction of differential expression

### ISSUE THREAD

**Issue by ScottBrostoff** [FrederickHuangLin/ANCOM#21]
Hi FrederickHuangLin,
Thank you for the great R code. One question however; the data does not seem to show anywhere in which direction a feature is differentially expressed (e.g. more in control subjects vs ill subjects). If i understand correctly, the x-axis in the plot is the effect size rather than the direction as is the case in DeSEQ. Is there a way to find out the direction of differential expression?

**Comment by FrederickHuangLin** [comment]
Hi @ScottBrostoff ,

Thanks for your interest in using ANCOM.

Unfortunately, ANCOM will not give you the direction based on its methodology; however, you can visualize the ANCOM results by the relative abundance (proportions between 0 and 1) plot, actually, this is what we have been doing in our group when using ANCOM, but keep in mind that ANCOM is designed for testing absolute abundances in a unit volume of an ecosystem, not relative abundances (proportions between 0 and 1), you need to be cautious in interpreting results using relative abundances.

For example, if ANCOM tells you taxon A is significant, then you can check the relative abundances of taxon A in, say treatment vs. control groups, and see in which group the relative abundance is higher. The conclusion would be something like "taxon A is differentially abundant (in a unit volume of an ecosystem) between treatment group and control group. The relative abundance of taxon A is higher in the treatment group based on the visualization."

We have realized the limitation of ANCOM and proposed a brand-new methodology for differential abundance analysis. The [paper](https://www.nature.com/articles/s41467-020-17041-7#:~:text=We%20introduce%20a%20methodology%20called,using%20a%20linear%20regression%20framework.) has been published in Nature Communications recently. The corresponding R package can be found [here](https://github.com/FrederickHuangLin/ANCOMBC).

Hope it helps!

Huang

**Comment by ScottBrostoff** [comment]
Hi Huang,

Thanks for the reply. 
I'm now looking into ANCOM-BC. My grouping variable is binary (ill= FALSE vs TRUE). In the diff_abn table I get some taxa that are TRUE in both the (Intercept) and the illTRUE columns. They have Beta values of 1.14e-4 en 3.80e-4, and q-values of 3.92e-10 and 0.021. 
I have a hard time interpreting this. It seems ANCOMBC is saying that this OTU is differentially expressed both in the ill=FALSE and ill=TRUE groups?

**Comment by FrederickHuangLin** [comment]
Hi @ScottBrostoff,

In this case, you should look at the beta value of `illTRUE` since `ill` is the variable of your interest. As it is positive, it means the corresponding taxon (in a unit volume of an ecosystem) is more abundant in `TRUE` group than `FALSE`.

Best,

Huang

**Comment by ScottBrostoff** [comment]
Ok. Thanks for the explanation!
