### ISSUE TITLE
Issue with prepro

### ISSUE THREAD

**Issue by dhrpa** [FrederickHuangLin/ANCOM#26]
Hi,
I am working with a tabular dataset with absolute abundance values in ANCOM2 with codes for adjusted for covariates.

I am able to load the package and my data well but as soon as I run the following line of codes my objects in the R environment turn to 0 observations or 0 variables:
feature_table = prepro$feature_table # leads to 0 variables
meta_data = prepro$meta_data # leads to 0 observations in the metadata
struc_zero = prepro$structure_zeros # Structural zero info

Because of which any further steps are invalid and give me errors.

Can you please help me with this?

Thank you in advance

**Comment by FrederickHuangLin** [comment]
Dear @dhrpa,

In order for me to better assist you with your issue, may you please provide me with your codes with related data sets attached (you can dummy all confidential information)?

Best,
Huang
