### ISSUE TITLE
ANCOM Speed

### ISSUE THREAD

**Issue by DJFast** [FrederickHuangLin/ANCOM#27]
Hi all, 

First I wanted to say thank you for making this wonderful program open source. Its people who do this who really help push science forward. So thank you. 

I am using ANCOM on human stool microbiome data. Specifically, shotgun metagenomic data, taxonomic data that has been classified by Kraken2. I have used ANCOM successfully for this procedure. However, this step 

res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula)

took me around 12 hours. Not 30seconds. I have seen issue #17 but I am not comfortable filtering my data. 

However, I have at my disposal a 24 core CPU so I thought I would run ANCOM in parallel to speed it up. Basically I transformed res= in to a function, exported to the cluster and ran it. It runs however, I think instead of using 20 cores as I instructs its just running the same code 20 times because its really slow. 

#make CPU cluster
detectCores()
cl <- makeCluster(20) #Make cluster, change CPU number to number of cores available 

clusterEvalQ(cl, {
  library(readr)
  library(tidyverse)
  library(tidyr)
  library(dplyr)
  library(readxl)
  library(nlme)
  library(dplyr)
  library(ggplot2)
  library(compositions)
})

clusterExport(cl, c('feature_table','meta_data','struc_zero','p_adj_method','p_adj_method','adj_formula','rand_formula',"ANCOM", "main_var"))

f1 <-function(i) {
t_start = Sys.time()
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            p_adj_method, adj_formula, rand_formula)
t_end = Sys.time()
t_run = t_end - t_start # around 30s
}

clusterExport(cl, c('f1'))

data.go <- lapply(cl, f1)

So I guess my question is, is there any valid way to make this process faster, or has anyone had success running ANCOM with parallel. Thanks in advanced.

**Comment by FrederickHuangLin** [comment]
Hi @DJFast,

Thanks for your interest in ANCOM and your valuable comment on parallel computing!

Unfortunately, the ANCOM R script was not written in the form of parallel computing, but we will definitely add this feature when publishing the corresponding R package.

Best,
Huang

**Comment by DJFast** [comment]
Hi @FrederickHuangLin 

Thanks for getting back to me on this. I appreciate the honesty. I look forward to the upcoming release of the R package. Keep up the great work. 

Best, 

David
