### ISSUE TITLE
when can use group_var and how to deal with parameter setting

### ISSUE THREAD

**Issue by Ivy-ops** [FrederickHuangLin/ANCOM#3]
Hi,
I am trying to understand the variables listed in the package. Some points make me lost. 

(1) There is one variable, group_var: Character. 

> The name of the group indicator. group_var is required for detecting structural zeros and outliers.

Hmm, I am considering when to use this variable and when not? Since I see in the demo example, moving-pics group_var =NULL, while in ecam example group_var = "delivery". Does that mean if I want to have random effect included, I need to add group_var = "", otherwise not. 

(2) Variable out_cut, zero_cut, lib_cut. Are there default parameters in this package? Since I really do not know which number shall be best. 

Your answers would be appreciated! :-)

-Ivy

**Comment by FrederickHuangLin** [comment]
Hi Ivy,

Thank you for using ANCOM! As for your questions:

1.  `group_var` is implemented in the preprocessing step before the ANCOM main function. For your reference, the preprocessing step is based on the [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) paper. To make a long story short, `group_var` is used to detect **structural zeros**. Say in your datasets, you have two locations: desert and rainforest. It will not be surprising to see that some taxa will be uniquely presented in the desert and totally absent in the rainforest, which means these taxa are structural zeros in the group of rainforest samples. If you would like to know which taxa are structural zeros, you can then specify `group_var = "location"` in the `feature_table_pre_process` function, and our preprocessing algorithm will detect the presence of structural zeros and automatically declare them to be differentially abundant.

2. Similarly, `out_cut`, `zero_cut`, `lib_cut` are all variables that can be specified in the `feature_table_pre_process` function. `out_cut` is for detecting outlier zeros, which is again based on the [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) paper, and it is useful for detecting some abnormal zeros we believe are outlying values. The default value for `out_cut` is 0.05, which means if zero counts make up of less than 5% of the proposed Gaussian mixture model, it will be detected as outlier zeros and replaced with `NA`. If you believe your dataset is exempt from erroneous data entries, you can also specify `out_cut = 0` to disable this detection. `zero_cut` is used for filtering non-informative taxa. For example, if you have 100 samples, and you set `zero_cut = 0.90` (default value), it will discard taxa with more than 90 zero entries (out of 100 samples you have). `lib_cut` is used for filtering samples, I **strongly** recommend that you adjust this variable based on your own dataset. For example, if you set `lib_cut = 1000`, then any sample with library size (total observed counts) less than 1000 will be discarded. However, library size varies a lot across different studies, some may have a lot of samples with library size less than 1000. In such cases, sticking with the default value will lose a lot of power. If you do not want to filter out any sample based on library sizes, you can simply set `lib_cut = 0` to disable this function.

Hope that helps,

Huang

**Comment by Ivy-ops** [comment]
Hi @FrederickHuangLin ,

Much appreciate your explanation. Pretty nice! It helps my understanding. Thank you!

-Ivy

**Comment by FrederickHuangLin** [comment]
> Hi @FrederickHuangLin ,
> 
> Much appreciate your explanation. Pretty nice! It helps my understanding. Thank you!
> 
> -Ivy

You are welcome!

Huang
