### ISSUE TITLE
Unexpected direction differential abundance

### ISSUE THREAD

**Issue by BoertienJM** [FrederickHuangLin/ANCOM#32]
Dear FrederickHuangLin,

Thanks for a great resource! Despite being somewhat of a black box for me in terms of its functionality, the tool can be easily used. Subsequently, I think my question can be reduced to a wrong interpretation to some of the output generated by ANCOM (v2.1). I therefore did not include any code in my question, but if required I can of course post this (although I almost literally used the code as provided in your tutorial).

When trying to deduct the direction of the differential abundance, I looked at the volcano plots. I assumed that a negative mean clr difference means a lower abundance compared to the reference/control group and a positive mean clr difference a higher abundance. According to below volcanoplot (at OTU/ASV level, there are three differentially abundant ASVs at a threshold of 0.7. Based on the clr mean difference, I would expect 2 ASVs with a lower and 1 with a higher abundance.

However, when I plot the relative abundances in the next figure (percentages plotted on a log10 after adding a pseudocount of 1), all three ASVs are lower in the group with cases (gray) compared to the controls (green). Also when plotting the clr transformed data (last figure), I get a similar pattern.

Therefore, I was wondering whether I interpret the "clr mean difference" wrongly or whether I might have made a mistake somewhere.

<img width="1100" alt="Screenshot 2021-05-26 at 13 43 17" src="https://user-images.githubusercontent.com/47536173/119712498-501f3c80-be69-11eb-8d95-c8752d288d7f.png">

<img width="550" alt="Screenshot 2021-05-26 at 13 44 56" src="https://user-images.githubusercontent.com/47536173/119713025-f0756100-be69-11eb-9a33-70395a82b7de.png">

<img width="550" alt="Screenshot 2021-05-26 at 13 49 46" src="https://user-images.githubusercontent.com/47536173/119713066-fbc88c80-be69-11eb-8b52-bb3baac2af0c.png">

**Comment by FrederickHuangLin** [comment]
Hi @BoertienJM,

Thanks for your question!

In the ANCOM source code, the CLR mean difference is coded as below

```

 # Draw volcano plot
 # Calculate clr
 clr_table = apply(feature_table, 2, clr)
 # Calculate clr mean difference
 eff_size = apply(clr_table, 1, function(y) 
   lm(y ~ x, data = data.frame(y = y, 
                               x = meta_data %>% pull(main_var),
                               check.names = FALSE))$coef[-1])

```

which involves two steps:
- CLR transformation
- Calculate the effect size using CLR transformed data as the dependent variable and the covariate of interest (such as group) as the independent variable

On the other hand, the box plot you made used the raw CLR values, and there comes the inconsistency.

Hope it helps,
Huang
