### ISSUE TITLE
prepro or feature_table_pre_process step fails, 

### ISSUE THREAD

**Issue by drelo** [FrederickHuangLin/ANCOM#35]
Dear all, I am using a MetaPhlAn 3 output (after the merge tables, only at the spp. level) formatted as input for ANCOM. 
I formatted the metadata as needed for ANCOM

I run the example data set and it worked fine. Now with my own data

```
otu_data = read_tsv("METADATA/abundance__features_ex.tsv", skip = 1)
otu_id = otu_data$`feature-id`
otu_data = data.frame(otu_data[, -1], check.names = FALSE)
rownames(otu_data) = otu_id

meta_data = read_tsv("METADATA/abundance_metadata_ex.tsv")[-1, ]
meta_data = meta_data %>% rename(Sample.ID = SampleID)
source("scripts/ancom_v2.1.R")

# Step 1: Data preprocessing
feature_table = otu_data; sample_var = "Sample.ID"; group_var = NULL
out_cut = 0.05; zero_cut = 0.90; lib_cut = 1000; neg_lb = FALSE
```

This all worked OK I got a feature_table and meta_data objects that seem OK
With the following code it seems I am doing something wrong.

```
prepro = feature_table_pre_process(feature_table, meta_data, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table # Preprocessed feature table
meta_data = prepro$meta_data # Preprocessed metadata
struc_zero = prepro$structure_zeros # Structural zero info
```

And then in this step I am using response as the main variable

```
# Step 2: ANCOM

main_var = "response"; p_adj_method = "BH"; alpha = 0.05
adj_formula = NULL; rand_formula = NULL
t_start = Sys.time()
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula)
```
produces this error: 

```
Error in alr_data[, -(1:i), drop = FALSE] : 
  número incorreto de dimensiones
```
The _prepro_ step seems to mess with the previous dataframes 

this is before that step
```
> dim(meta_data)
[1] 344   5
> dim(feature_table)
[1] 807 344
> dim(otu_data)
[1] 807 344
```
and after
```
> dim(meta_data)
[1] 0 5
> dim(feature_table)
[1] 208   0
```

Maybe it is a minor mistake in the data but I would appreciate if you can help me with this
I am attaching the tsv data

[abundance__features_ex.txt](https://github.com/FrederickHuangLin/ANCOM/files/6993977/abundance__features_ex.txt)
[abundance_metadata_ex.txt](https://github.com/FrederickHuangLin/ANCOM/files/6993978/abundance_metadata_ex.txt)

Best,

Andrès

**Comment by mmanus** [comment]
Hi @drelo - did you ever resolve this issue? The same thing is happening to me, with the prepro step affecting my metadata file in a similar way that you describe here (effectively wiping clean the metadata file). I get the same error in the next step, with the incorrect number of dimensions.

Thanks!
- Melissa

**Comment by drelo** [comment]
Nop I couldn't make it work: / I had to deal with another dataset so I
forgot about this one.

**Comment by FrederickHuangLin** [comment]
Hi @drelo and @mmanus,

My apologies for the delayed response! I checked your data, the culprit is `lib_cut = 1000`.

It seems your data have very shallow library sizes:
```
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
49.44   93.40   97.52   93.90   99.28  100.00 
```
so setting the library cut at 1000 will remove every sample since the criterium basically discards samples with the corresponding library sizes less than 1000.

Best,
Huang

**Comment by drelo** [comment]
I didn't notice that, so I will follow that advice then. Thanks for the
help!
