### ISSUE TITLE
Add a pseudo-count before drawing volcano plots

### ISSUE THREAD

**Issue by yxia0125** [FrederickHuangLin/ANCOM#37]
Hi

I noticed the main code of ANCOM2 did not add a pseudo-count of 1 to the feature table before drawing the volcano plot. Will you consider to add a pseudo-count of 1 before drawing the volcano plot? So that all low-abundance taxa can be positive.

**Comment by FrederickHuangLin** [comment]
Hi @yxia0125 ,

ANCOM automatically adds a pseudo-count of 1 in its function. For details, you can check line 139 [here](https://github.com/FrederickHuangLin/ANCOM/blob/master/programs/ancom.R).

Best,
Huang
