### ISSUE TITLE
plotting of ANCOM (& picrust2) results?

### ISSUE THREAD

**Issue by marwa38** [FrederickHuangLin/ANCOM#41]
Hi 
Hello .. Could you please suggest a way to plot something like this?
![image](https://user-images.githubusercontent.com/68851733/151986853-3260872c-3dea-4d84-8ce5-203773388133.png)
![image](https://user-images.githubusercontent.com/68851733/151986876-df93cbf8-4119-4901-ac19-a2fd2c174516.png)

Cheers

**Comment by FrederickHuangLin** [comment]
Hi @marwa38,

I guess the plots you provided are trying to visualize effect sizes such as log fold changes. Unfortunately, ANCOM does not return effect sizes. You can visualize the W statistics of ANCOM in the same way these plots did but I don't think it is meaningful.

Best,
Huang
