### ISSUE TITLE
Error in ANCOM analysis

### ISSUE THREAD

**Issue by MrX-NGS** [FrederickHuangLin/ANCOM#6]
Hi,

I am trying to setup my analysis with ANCOM version 2.1. Currently, I encounter a problem with empty output from preprocessing function as below:
otufmttrasposed <- read.csv("otu.fmt.transposed.txt",sep="\t",check.names = F)
metafmt <- read.csv("meta.fmt.txt",sep="\t",check.names = F)
feature_table_pre_process(feature_table = otufmttrasposed,meta_data = metafmt,sample_var="Sample.ID",group_var = NULL, out_cut = 0.05, zero_cut = 0.90, lib_cut = 1000, neg_lb)
$feature_table
data frame with 0 columns and 48 rows

$meta_data
 [1] Sample.ID      antiexposedall day_of_life    delivery      
 [5] diet           diet_3         mom_child      month         
 [9] month_of_life  sample_summary sex            studyid       
<0 rows> (or 0-length row.names)

$structure_zeros
NULL

I require the structure_zeros  and feature table matrix output from this to run the ANCOM function. I miss those currently.

I also tried to give the group variable as below and encounter the below error:
`otufmttrasposed <- read.csv("otu.fmt.transposed.txt",sep="\t",check.names = F)`
`metafmt <- read.csv("meta.fmt.txt",sep="\t",check.names = F)`
`feature_table_pre_process(feature_table = otufmttrasposed,meta_data = metafmt,sample_var="Sample.ID",group_var = "antiexposedall", out_cut = 0.05, zero_cut = 0.90, lib_cut = 1000,  neg_lb=1)`

**Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent**

Any solution to this problem will be appreciated!! Attached is the files to reproduce these errors!

Thanks in advance!

Best Regards,
Bala

[meta.fmt.txt](https://github.com/FrederickHuangLin/ANCOM/files/4354205/meta.fmt.txt)
[otu.fmt.transposed.txt](https://github.com/FrederickHuangLin/ANCOM/files/4354207/otu.fmt.transposed.txt)

**Comment by FrederickHuangLin** [comment]
Hi,

Thanks for using ANCOM!

I checked your datasets, it seems the format of OTU/SV table is not correct. In order to use ANCOM, one should have OTU/SV table with taxa in rows (`rownames`) and samples in columns (`colnames`); However, your `otufmttrasposed` has no values of `rownames`, and the first column named `Sample.ID` actually stores taxa IDs.

Please try the following codes:
```
otufmttrasposed = read.csv("otu.fmt.transposed.txt",sep="\t",check.names = F)
metafmt = read.csv("meta.fmt.txt",sep="\t",check.names = F)

otu_id = otufmttrasposed$Sample.ID
otu_data = data.frame(otufmttrasposed[, -1], check.names = FALSE)
rownames(otu_data) = otu_id

source("ancom_v2.1.R")
feature_table = otu_data; sample_var = "Sample.ID"; group_var = NULL
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = FALSE
prepro = feature_table_pre_process(feature_table, metafmt, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table 
meta_data = prepro$meta_data 
struc_zero = prepro$structure_zeros 
```

Also, I noticed that `otufmttrasposed` is a relative abundance table. Note that ANCOM is designed for analyzing absolute abundance table, NOT relative abundance table. You do not have to transform the original OTU/SV table into proportions.

I also updated the user manual to make it clearer.

Hope it helps,

Huang

**Comment by MrX-NGS** [comment]
Dear Huang,

Thanks for your reply! I used the ecam dataset just for testing the new version. 

I tried your suggestion and still getting the NULL structural zeros for some reason. I attach the files from my own data as they are absolute counts and you can replicate the error. 

`otu = read.csv("genus.table.dataset1.test.txt",sep="\t",check.names = F)
metadata = read.csv("map.dataset1.final.txt",sep="\t",check.names = F)
otu_id = otu$Sample.ID
otu_data = data.frame(otu[, -1], check.names = FALSE)
rownames(otu_data) = otu_id
source("ancom_v2.1.R")
feature_table = otu_data; sample_var = "Sample.ID"; group_var = NULL
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = FALSE
prepro = feature_table_pre_process(feature_table, metafmt, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table 
meta_data = prepro$meta_data 
struc_zero = prepro$structure_zeros 
attributes(feature_table)
attributes(meta_data)
attributes(struc_zero)`

Output:

attributes(struc_zero)
NULL

Hope the problem is traceable!

[map.dataset1.final.txt](https://github.com/FrederickHuangLin/ANCOM/files/4363703/map.dataset1.final.txt)
[genus.table.dataset1.test.txt](https://github.com/FrederickHuangLin/ANCOM/files/4363705/genus.table.dataset1.test.txt)

Thanks in advance for your help!

Best Regards,
Bala

**Comment by FrederickHuangLin** [comment]
Hi Bala,

It is because you haven't specified the `group_var`. In order to identify structural zeros, say with respect to the variable `group`, you should specify `group_var = group`. For details, you can go to the "Instructions for use" section on the user manual, or the last three examples on the user manual.

Best,

Huang

**Comment by MrX-NGS** [comment]
I am getting the below error when i add the group variable in metadata: 

prepro = feature_table_pre_process(feature_table, metadata, sample_var, group_var="DWDS", 
+                                    out_cut, zero_cut, lib_cut, neg_lb)
 Show Traceback
 
 Rerun with Debug
 Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

**Comment by FrederickHuangLin** [comment]
Hi Bala,

I checked your new dataset. This time, your new OTU/SV table actually has samples in rows, and taxa in columns, which does not satisfy the input requirement for data preprocessing and ANCOM main function.

The proper format for OTU/SV table is: 

> `feature_table`: Data frame or matrix representing observed OTU/SV table with taxa in rows (`rownames`) and samples in columns (`colnames`). Note that this is the absolute abundance table, do not transform it to relative abundance table (where the column totals are equal to 1).

You can try the following codes
```
otu = read.csv("genus.table.dataset1.test.txt",sep="\t",check.names = F)
metadata = read.csv("map.dataset1.final.txt",sep="\t",check.names = F)
sample_id = otu$Sample.ID
otu_id = colnames(otu)[-1]
otu_data = data.frame(t(otu[, -1]), check.names = FALSE)
colnames(otu_data) = sample_id

source("ancom_v2.1.R")
feature_table = otu_data; sample_var = "Sample.ID"; group_var = "DWDS"
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = FALSE
prepro = feature_table_pre_process(feature_table, metadata, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
```
You can look into `otu_data` (try `View(otu_data)`) and get a rough idea about what the required format looks like.

Best,

Huang

**Comment by MrX-NGS** [comment]
It worked! Thanks a lot

**Comment by dhrpa** [comment]
@FrederickHuangLin 
Hello, 
I am facing similar issues while using ANCOM. I was hoping you can help me with the same. 
I am trying to use the same code you suggested earlier 
otu = read.csv("genus.table.dataset1.test.txt",sep="\t",check.names = F)
metadata = read.csv("map.dataset1.final.txt",sep="\t",check.names = F)
sample_id = otu$Sample.ID
otu_id = colnames(otu)[-1]
otu_data = data.frame(t(otu[, -1]), check.names = FALSE)
colnames(otu_data) = sample_id

source("ancom_v2.1.R")
feature_table = otu_data; sample_var = "Sample.ID"; group_var = "Fishtype"
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = FALSE
prepro = feature_table_pre_process(feature_table, metadata, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)

But I am getting the error:
 Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

I tried keeping group var NULL but my my attribute of struc zero is NULL.
Also my sample_id, otu_id are reamining null for some reason. Can you please help me with this.

Please find attached my biom table for your reference.
[table.from_biom_w_taxonomy.txt](https://github.com/FrederickHuangLin/ANCOM/files/5091236/table.from_biom_w_taxonomy.txt)



Thank you in advance

Kind regards
Dhrati

**Comment by FrederickHuangLin** [comment]
Hi Dhrati,

ANCOM requires a `feature_table` to be a data frame or matrix representing observed OTU/SV table with taxa in rows (`rownames`) and samples in columns (`colnames`).

By checking your attached file, the first row of your data is

`# Constructed from biom file`

which means `otu_id = colnames(otu)[-1]` will return NULL, since `colnames(otu)` is `# Constructed from biom file`. Also, `sample_id = otu$Sample.ID` will return NULL since there is no column called `Sample.ID`.

You can try something like

```
otu = read.csv("genus.table.dataset1.test.txt",sep="\t",check.names = F, skip = 1) # skip the first line
otu_id = otu$Sample.ID # in your data, the column "Sample.ID" is actually the OTU ID
sample_id = colnames(otu)[-1] # be careful about the last column. In your attached file, the last column is taxonomy 
otu_data = data.frame((otu[, -1]), check.names = FALSE)
rownames(otu_data) = otu_id
colnames(otu_data) = sample_id
```

Best,

Huabg

**Comment by dhrpa** [comment]
@FrederickHuangLin 
Hi Huang,
Thank you for your reply. So I removed the last column of taxonomy from my file (attached for your reference
[table.from_biom.txt](https://github.com/FrederickHuangLin/ANCOM/files/5200340/table.from_biom.txt)
) and went ahead with the script for repeated measures as I am trying to detect differentialy abundant taxa in two groups.

The script I used are as mentioned on the github page for repeated measures:

library(readr)
library(tidyverse)

otu = read.csv("table.from_biom.txt", sep= "\t", check.names = F, skip = 1)
otu_id = otu$Sample.ID
sample_id = colnames(otu)[-1]
otu_data = data.frame((otu[, -1]), check.names = FALSE)
rownames(otu_data) = otu_id
colnames(otu_data) = sample_id

meta_data = read.csv("iFishMappingCalypsoAll.csv")[-1, ]
meta_data = meta_data %>% rename(Sample.ID = SampleID)

source("ancom_v2.1.R")

# Step 1: Data preprocessing

feature_table = otu_data; sample_var = "Sample.ID"; group_var = "FishYesNo"
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = TRUE
prepro = feature_table_pre_process(feature_table, meta_data, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table # Preprocessed feature table
meta_data = prepro$meta_data # Preprocessed metadata
struc_zero = prepro$structure_zeros # Structural zero info

# Step 2: ANCOM

main_var = "FishYesNo"; p_adj_method = "BH"; alpha = 0.05
adj_formula = NULL; rand_formula = "~ 1 | Label"; control = list(msMaxIter = 50)
t_start = Sys.time()
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula, control = control)


t_end = Sys.time()
t_run = t_end - t_start # around 30s

**write_csv(res, "output.csv")**

##the above command did not work

# Number of taxa except structural zeros
n_taxa = ifelse(is.null(struc_zero), nrow(feature_table), sum(apply(struc_zero, 1, sum) == 0))
# Cutoff values for declaring differentially abundant taxa
cut_off = c(0.9 * (n_taxa -1), 0.8 * (n_taxa -1), 0.7 * (n_taxa -1), 0.6 * (n_taxa -1))
names(cut_off) = c("detected_0.9", "detected_0.8", "detected_0.7", "detected_0.6")

# Annotation data
dat_ann = data.frame(x = min(res$fig$data$x), y = cut_off["detected_0.7"], label = "W[0.7]")

fig = res$fig + 
  geom_hline(yintercept = cut_off["detected_0.7"], linetype = "dashed") + 
  geom_text(data = dat_ann, aes(x = x, y = y, label = label), 
            size = 4, vjust = -0.5, hjust = 0, color = "orange", parse = TRUE)
fig   


**####
Once I got the following error with forming res :
Error in solve.default(-val) : 
  system is computationally singular: reciprocal condition number = 5.41494e-18

Second time, 
The command write_csv (res, "output.csv") does not give me with an output file. It throws an error like: 
Error in write_delim(x, path, delim = ",", na = na, append = append, col_names = col_names,  : 
  is.data.frame(x) is not TRUE

Does it mean my files are still wrong? I basically want to check if the two groups I have include differentially abundant taxa and the differences are significant or no.**

thank you in advance

Any help will be appreciated


Kind regards
Dhrati

**Comment by FrederickHuangLin** [comment]
Hi Dhrati,

I am not quite sure about your first error, but the second one was due to a typo in the tutorial. My apologies! Try:

`write_csv(res$out, "output.csv")`

Because `res` is a `list` not a `data.frame`, `res$out` is exactly what you want.

Best,

Huang
