### ISSUE TITLE
 Error in formula.default(object) : invalid formula

### ISSUE THREAD

**Issue by tmurillocorrales** [FrederickHuangLin/ANCOM#7]
Hi,

I am trying the script for longitudinal analysis. However, I am getting the following error : Error in formula.default(object) : invalid formula. I think it might come from when I define the random effects, since I tried the standard analysis with the same dataset and it works perfectly. Are there any special considerations I should know for defining the random effects? I have a factor with 5 levels, 5 individuals and I am comparing 2 seasons (factor with 2 levels). Do you have some advice to fix this error?

Thanks,
Tatiana

**Comment by FrederickHuangLin** [comment]
Hi Tatiana,

Thanks for using ANCOM!

You are right, this error message probably occurs when defining an improper random effect formula. In order for me to better look into your problem, could you please provide a reproducible example of this error (i.e. your lines of codes and an example dataset)?

Best,

Huang

**Comment by tmurillocorrales** [comment]
####### ANCOMMM ######
library(exactRankTests)
library(nlme)
library(dplyr)
library(ggplot2)
library(compositions)
library(readr)
library(tidyverse)
source("ANCOM-2.1/scripts/ancom_v2.1.R")

# Data preparation #####
otu_data = read.csv("otu_data.txt", sep = "\t", row.names = 1, check.names = F)

meta_data = read.csv("meta_data.txt", sep = "\t")
meta_data = meta_data %>% rename(SampleID = Sample.ID)
str(meta_data)

#Convert to factor

meta_data <- data.frame(lapply(meta_data, as.factor))
str(meta_data)

## Repeated measure/longitudinal analysis #####

# Step 1: Data preprocessing

feature_table = otu_data; sample_var = "SampleID"; group_var = "season"
out_cut = 0.05; zero_cut = 0.90; lib_cut = 0; neg_lb = TRUE
prepro = feature_table_pre_process(feature_table, meta_data, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table # Preprocessed feature table
meta_data = prepro$meta_data # Preprocessed metadata
struc_zero = prepro$structure_zeros # Structural zero info

# Step 2: ANCOM

main_var = "season"; p_adj_method = "BH"; alpha = 0.05
adj_formula = NULL; rand_formula = "~ 1 | individual"; control = list(msMaxIter = 50)
t_start = Sys.time()
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula, control)
t_end = Sys.time()
t_run = t_end - t_start

[ancomm_script.txt](https://github.com/FrederickHuangLin/ANCOM/files/4598348/ancomm_script.txt)
[meta_data.txt](https://github.com/FrederickHuangLin/ANCOM/files/4598333/meta_data.txt)
[otu_data.txt](https://github.com/FrederickHuangLin/ANCOM/files/4598335/otu_data.txt)

**Comment by FrederickHuangLin** [comment]
Hi,

Thanks for sending the sample code and dataset! I realized the problem comes from unnamed argument `control`, try the following:

`res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula, control = control)`

I will address this problem for the next version of ANCOM, thanks for catching this!

Best,

Huang

**Comment by tmurillocorrales** [comment]
Hi Huang,

Thanks for the help! I made the suggested changes and now it works.

Have a nice day!
Tatiana

**Comment by tmurillocorrales** [comment]
Hi Huang,

I have another question. I  was working with Random coefficients/slope model and had the following error:

 Error in lme.formula(fixed = tformula, data = data.frame(x, alr_data,  :  nlminb problem, convergence error code = 1 message = iteration limit reached without convergence (10) .

From older issues I noticed that I should increase the number of max iterations for nlme.

Can you tell me how can I do that?

Thanks,
Tatiana

**Comment by FrederickHuangLin** [comment]
Hi Tatiana,

In dealing with mixed effects models, ANCOM passes arguments to the `lme` function from [nlme](https://cran.r-project.org/web/packages/nlme/nlme.pdf) package. 

When convergence error occurs, usually, you can increase the maximum number of iterations or change the optimizer :

`control = lmeControl(maxIter = 100, msMaxIter = 100, opt = "optim")`

`res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula, control = control)`

Also, it is good to check whether it is truly meaningful to include the random effects in your model. You can find a more detailed discussion [here](https://stackoverflow.com/questions/7923387/error-with-nlme).

Hope it helps,

Huang

**Comment by tmurillocorrales** [comment]
Hi Huang,

Thanks for all the help.

Tatiana
