### ISSUE TITLE
Can you please provide the code to download ANCOM2 for R?

### ISSUE THREAD

**Issue by anahitab02** [FrederickHuangLin/ANCOM#8]

**Comment by anahitab02** [comment]
Hello! I was wondering if you can post the R package required to do the ANCOM II analysis? I have searched a lot and even went back to the original papers but could not find the download instructions for it. I would really appreciate your help with the same.

**Comment by FrederickHuangLin** [comment]
Hi,

Unfortunately, there is no R package for ANCOM-II but you can download the R scripts in the Supplementary Material of [ANCOM-II paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/), which can be used to reproduce figures.

Note that although there are some slight differences, most of ANCOM-II functions have been adopted to `feature_table_pre_process` function in this repository.

Best,

Huang

**Comment by anahitab02** [comment]
oh ok. Thank you for your response. I downloaded all the required packages,

> library(exactRankTests)
> library(nlme)
> library(dplyr)
> library(ggplot2)
> library(compositions)

but when I run the code, I am getting this error,

> Error in feature_table_pre_process(feature_table, meta_data, sample_var,  : 
>   could not find function "feature_table_pre_process"

I am quite new to this and would really appreciate it if you could help me figure this out. Thank you again!

**Comment by FrederickHuangLin** [comment]
Hi, 

You have to load the ANCOM function. For example, the ANCOM script is saved under the folder "scripts" in your current working directory, you can run the following code to load the ANCOM function.

`source("scripts/ancom_v2.1.R")`

Hope it helps :)

Huang
